### ISSUE TITLE
QA code image doesn't appear - 402 error

### ISSUE THREAD

**Issue by mattnook** [ElementsProject/woocommerce-gateway-lightning#16]
Hi, I am trying to use the Lightning Payment Gateway and the invoice is working fine, however the QR code no longer appears. The console is giving me a 402 error which is unusual. I am using the Divi theme but previously did not have issues. Any idea what this could be?
![console 402 error](https://user-images.githubusercontent.com/16688198/56105522-47c24c80-5f02-11e9-8700-c27a9c33780e.png)
![missing image](https://user-images.githubusercontent.com/16688198/56105528-53157800-5f02-11e9-844b-aae403294def.png)

**Comment by shesek** [comment]
The 402 status code (which means `Payment Required`) is expected and is not the cause of your issue.

It seems to me like the cause is the [Jetpack's lazy images](https://jetpack.com/support/lazy-images/) feature, which appears to not function properly with [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) images.

According to Jetpack's documentation (linked above), you can turn this feature off under `Jetpack → Settings → Performance → Performance and Speed → Lazy loading for images`.

If turning this off fixes the issue, you should file a report with Jetpack telling them that the lazy images feature breaks images loaded via data URIs.

**Comment by mattnook** [comment]
thanks! that worked
